use_frameworks!

platform :ios, '8.0'

target 'MHBasicsComponent_Example' do
  pod 'MHBasicsComponent', :path => '../'

  target 'MHBasicsComponent_Tests' do
    inherit! :search_paths

    
  end
end
